app:
  nombre: ORIGAMIGT
  origamiGT: http://192.188.3.49:8713
  paramVisor: sisapp98
  imagenDoc: http://192.188.3.49:8712/bcbg/api/firmaElectronica/docImagen/
  rutaArchivos: C:/archivos/firmasElectronicas/
  archivosPCLocal: C:/archivos/documentos/
  imagenesPCLocal: C:/archivos/imagenes/
  ext: .p12
  keyFiles: 12345

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 3
    appname: FIRMAEC-ZERVICES
  client:
    register-with-eureka: false
    fetch-registry: false

