server:
  port: 7777


spring:
  application:
    name: sigeri-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/origami-ec/config-temp.git
          skipSslValidation: true
          default-label: main
          username: origami-ec
          password: ${SPRING_CLOUD_CONFIG_PASSWORD}
