server:
  port: 7777


spring:
  application:
    name: sigeri-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/origami-ec/config-files-machala.git
          skipSslValidation: true
          default-label: main
          username: origami-ec
          password: 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
