server:
  port: 7777


spring:
  application:
    name: sigeri-config-server


  cloud:
    config:
      server:
        git:
          uri: file:///opt/config-files-machala
          default-label: main
          clone-on-start: true
